global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "task-service"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["task-api:9191"]

  - job_name: "user-service"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["user-service:9193"]

  - job_name: "notification-service"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["notification-service:9292"]

  - job_name: "jaeger"
    static_configs:
      - targets: ["jaeger:14269"]

  - job_name: "kafka"
    static_configs:
      - targets: ["ckafka:5556"]
