services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - 4318:4318
      - 16686:16686
      - 14269:14269
      - 14268:14268
    environment:
      COLLECTOR_OTLP_ENABLED: "true"
    networks:
      - shared

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - 7000:9090
    volumes:
      - ./files/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - shared

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - 7001:3000
    networks:
      - shared
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    volumes:
      - grafana-storage:/var/lib/grafana

networks:
  shared:
    external: true
    name: shared-network-microservice

volumes:
  grafana-storage: {}