global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'task-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['http://<task-service-host>:9191']
  
  - job_name: 'user-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['http://<user-service-host>:9193']
  
  - job_name: 'notifications-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['http://<notifications-service-host>:9292']

  - job_name: 'kafka'
    # metrics_path: /metrics
    static_configs:
      - targets: ['http://<kafka-host>:5556']

  - job_name: 'jaeger'
    static_configs:
      - targets: ['jaeger:16686']
