---
- name: Setup monitoring EC2 instances
  hosts: jenkins
  become: true

  vars:
    jenkins_repo_url: http://pkg.jenkins.io/debian-stable
    jenkins_repo_key_url: https://pkg.jenkins.io/debian/jenkins.io-2023.key


  tasks:
    - name: Update and upgrade the system
      apt:
        update_cache: yes
        upgrade: dist
      when: ansible_os_family == "Debian"

    - name: Install required packages
      apt:
        name:
          - openjdk-21-jdk
          - curl
          - gnupg2
          - ca-certificates
          - apt-transport-https
          - software-properties-common
        state: present
      when: ansible_os_family == "Debian"
      
    - name: Set Java 21 as default
      alternatives:
        name: java
        link: /usr/bin/java
        path: /usr/lib/jvm/java-21-openjdk-amd64/bin/java
      when: ansible_os_family == "Debian"

    - name: Download Jenkins GPG key
      get_url:
        url: https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key
        dest: /etc/apt/keyrings/jenkins-keyring.asc
        mode: '0644'

    - name: Add Jenkins APT repository
      apt_repository:
        repo: "deb [signed-by=/etc/apt/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian-stable binary/"
        state: present
        filename: jenkins



    - name: Install Jenkins
      apt:
        name: jenkins
        state: present
      when: ansible_os_family == "Debian"

    - name: Ensure Jenkins is started and enabled
      systemd:
        name: jenkins
        state: started
        enabled: true

    
